server:
  port: 9023
spring:
  application:
    name: resource
  zipkin:
      base-url: http://localhost:9050
eureka:
  instance:
    prefer-ip-address: true #
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
  client:
      service-url:
        defaultZone: http://register1:9010/eureka/,http://register2:9011/eureka/
###actuator监控点 start####
endpoints:
  health:
    sensitive: false
    enabled: true
##默认情况下很多端点是不允许访问的，会返回401:Unauthorized
management:
  security:
    enabled: false
###actuator监控点 end####
security:
  #白名单配置
  ignored: /**/**
#   oauth2:
#     resource:
#       id: resource
#       user-info-uri: http://localhost:9030/uaa/user
#       prefer-token-info: false